import React from 'react'
export const metadata = {
  title: "珠海人才网-Boss直聘-珠海公司招聘信息",
  description: "Generated by create next app",
};
const layout = ({ children }) => {
  return (
    <div>
      {children}
    </div>
  )
}

export default layout
