/*
 * @Description: --☀☺☀--
 * @Author: Jhon
 * @Date: 2024-05-29 14:50:04
 * @LastEditors: Jhon
 */
import { Inter } from "next/font/google";
import "./globals.css";
const inter = Inter({ subsets: ["latin"] });
import { Providers } from "@/themeProvider";
import Navbar from "@/components/Navbar";

export const metadata = {
  title: "Boss直聘",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className + ' bg-gradient-to-r from-[#ECFCFF] dark:from-[#2a3635] from-10%  dark:via-[#203630ef] to-[#ECFCFF] dark:to-[#23696959] to-100%'}>
        <Providers>
          <main className="min-h-screen">
            <Navbar />
            {children}
            {/* <Footer /> */}
          </main>
        </Providers>
      </body>
    </html>
  );
}
