import React from "react";
export const metadata = {
  title: "Boss直聘2323",
  description: "Generated by create next app1212",
};
export default function layout({ children }) {
  return (
    <div>
      layout
      {children}
    </div>
  );
}
