'use client'
import React,{useState} from "react";
import MessageList from "./components/MessageList";
import MessageRoom from "./components/MessageRoom";
import 'animate.css'
// export const metadata = {
//   title: "Boss直聘-我的消息",
//   description: "Generated by create next app",
// };
export default function Message() {
  const [flag,setFlag] = useState(false);
  const handleClose = () => {
setFlag(!flag)
  }
  return (
    <div
      className="container mx-auto py-4 relative"
      style={{ height: "calc(100vh - 64px)" }}
    >
      <div className="absolute top-0 bottom-0 md:top-4 md:bottom-4 left-0 right-0 ">
        <div className="flex gap-5 h-full w-full">
          <div className="flex-1 hidden xl:flex-[.3] xl:block  h-full overflow-auto">
            <MessageList />
          </div>
          <div className="flex-1 xl:flex-[.65] h-full relative">
            {flag && <div onClick={() => handleClose()} className={`absolute h-full z-[999] overflow-hidden backdrop-blur-lg left-0 right-0 top-0 bottom-0  bg-gray-300/20 `}>
              <div className={`w-[450px] overflow-auto h-full animate__animated ${flag ? 'animate__slideInLeft' : 'animate__slideOutLeft'}`}>
                <MessageList />
              </div>
            </div>}
            <MessageRoom handleClose={handleClose} flag={flag} />
          </div>
        </div>
      </div>
    </div>
  );
}
