import React from "react";
import MessageList from "./components/MessageList";
export const metadata = {
  title: "Boss直聘-我的消息",
  description: "Generated by create next app",
};
export default function Message() {
  return (
    <div className="container mx-auto py-4 relative" style={{height: 'calc(100vh - 64px)'}}>
      <div className="absolute top-4 bottom-4 left-0 right-0 ">
        <div className="flex gap-5 h-full w-full">
          <div className="flex-[.3] h-full overflow-auto">
            <MessageList />
          </div>
          <div className="flex-[.65]">hello</div>
        </div>
      </div>
    </div>
  );
}
